### ISSUE TITLE
项目目前无法正常使用,大佬还会继续维护更新嘛!

### ISSUE THREAD

**Issue by Waite0603** [haarlemmer/CTFile-Auto-Download#3]
如题, 项目目前无法正常运行! 想知道大佬还会不会维护更新!

**Comment by hihaar** [comment]
我正使用电子邮件回复，因为我丢失了Github双重认证密钥和恢复代码，我目前无法登录我的github账户，该项目仍然在继续开发，会在找回账户后push上来（找不回来的话我会开个新号，发到这个issue里



________________________________
发件人: Waite Wang ***@***.***>
发送时间: 2023年10月26日 23:26
收件人: haarlemmer/CTFile-Auto-Download ***@***.***>
抄送: Subscribed ***@***.***>
主题: [haarlemmer/CTFile-Auto-Download] 项目目前无法正常使用,大佬还会继续维护更新嘛! (Issue #3)


如题, 项目目前无法正常运行! 想知道大佬还会不会维护更新!

―

**Comment by hihaar** [comment]
已经适配城通最新API，实测已经可用，现在Push.
